### ISSUE TITLE
World rotates when Avatar is moved with keyboard

### ISSUE THREAD

**Issue by boodie** [adlnet/Sandbox#224]
SERVER:
Node JS 0.12.4

Model Name:	Mac mini
  Model Identifier:	Macmini3,1
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	2.53 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	3 MB
  Memory:	8 GB

CLIENT:
 Model Name:	iMac
  Model Identifier:	iMac11,1
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  
 Chipset Model:	ATI Radeon HD 4850
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Total):	512 MB

Using Chrome Version 43.0.2357.81 (64-bit)

The interface acts in an unexpected way- or at least unexpected to me! When you are using the arrow keys to move about the whole world moves around too. The camera should move and follow the avatar but the whole world should not spin too. I am used to the way OpenSim and SL movement controls work. This should work pretty much the same I would think.

**Comment by rchadwic** [comment]
Hey Boodie. I think that maybe the behavior you're seeing is by design. Do you see the avatar walk in a small circle? The camera would track the avatar during this motion. Does that sound like what you see?
