### ISSUE TITLE
Deleting modifier via hierarchy view doesn't undo its changes

### ISSUE THREAD

**Issue by mickmuzac** [adlnet/Sandbox#225]
Steps to reproduce: 

0. Create cylinder
0. Create twist modifier on cylinder
0. Increase twist amount so it's noticeable
0. Deselect cylinder
0. Use hierarchy view to select the modifier directly
0. Use properties widget to delete modifier

After following these steps, the modifier's VWF node is deleted, however the effect it had on the prim is not undone.

**Comment by rchadwic** [comment]
Fixed. Prims now rebuild the stack when a child node is removed. In the future, we should ensure that the child node was a modifier.
