### ISSUE TITLE
Having multiple skinned models in scene confuses selection highlight

### ISSUE THREAD

**Issue by stevenvergenz** [adlnet/Sandbox#232]
![mixed up skinning highlight](https://cloud.githubusercontent.com/assets/1882376/8207463/aa63b76a-14cf-11e5-9d3b-53ebcf686e5c.png)

The model is the same one I've been testing with: http://aws.vergenz.info:3500/sas/assets/4d1fea82

**Comment by rchadwic** [comment]
This seems to have been fixed by the refactor in assetLoader
