### ISSUE TITLE
Go to Position bug

### ISSUE THREAD

**Issue by cr8onski** [adlnet/Sandbox#235]
In a blank world with no avatar using go to position, under the location menu, with any value produces these error messages and it seems to be searching indefinitely for the avatar to move.

TypeError: _UserManager.GetAvatarForClientID(...) is undefined AvatarCameraController.js:113:21
and
TypeError: _UserManager.GetAvatarForClientID(...).transformAPI is undefined AvatarCameraController.js:113:21

**Comment by rchadwic** [comment]
Yup, this menu needs to be disabled when no avatar is present.

**Comment by stevenvergenz** [comment]
Fixed for 1.0
