### ISSUE TITLE
Log out reloads world

### ISSUE THREAD

**Issue by wilo1** [adlnet/Sandbox#241]
The log out buttons on both the toolbar and file area do not log the user out. It will reload the current world instead.

**Comment by rchadwic** [comment]
Yup, this is a bug. The whole "log out" buttons needs to be re-thought. For now, we should load the world landing page.

**Comment by wilo1** [comment]
Any plans to correct this bug? Would a good workaround for our students be to simply save and then exit by closing the chrome tab? Maybe we should take out the log out button until it's addressed?

**Comment by rchadwic** [comment]
Yeah, this is super simple. Sorry we have not got to it ATM, working on deeper problems. I'll fix today. Is this in the Master branch, or are you working in Dev?

**Comment by wilo1** [comment]
Master. Thanks!WILOSTAR3D LLChttp://www.wilostar3d.com27499 Riverview Center Blvd. Suite 246Bonita Springs, Florida 34134p/1-877-711-8117f-1-877-679-3775"Creating Creators!" 


-------- Original Message --------
Subject: Re: [Sandbox] Log out reloads world (#241)

**Comment by rchadwic** [comment]
So, this looks like a conflict between the custom app path and the regex, which assumed the URL contained /adl/sandbox/. Just pushed a more robust fix that is tested to work with custom app path.
