### ISSUE TITLE
How create a user via api using php or nodejs? Is possible?

### ISSUE THREAD

**Issue by neylsongularte** [adlnet/Sandbox#258]

**Comment by rchadwic** [comment]
Yes, you can hit the Web API to create a new user account.

`http://localhost:3000/vwfDataManager.svc/CreateProfile?UID=NewUniqueID`

the request should be a **POST** command with a JSON body of the format

```
profile.Username = username;
profile.Email = email;
profile.Password = password;
profile.Salt = salt;
```

You should generate a unique salt, then generate the password as such:

```
var EncryptPassword = function (password, username,salt)
{
	var unencrpytedpassword = password + username + salt;
	for (var i = 0; i < 1000; i++) 
	{
		unencrpytedpassword = CryptoJS.SHA256(unencrpytedpassword) + '';
	}
	return unencrpytedpassword;
}
```

So, the value of password you send the server is the result of this function. **Never send the plaintext password to the API.**

The server will validate uniqueness for the UID, and the format of the UID and email.

**Comment by neylsongularte** [comment]
I solved a bug
https://github.com/adlnet/Sandbox/pull/259

**Comment by rchadwic** [comment]
Ah hey, I don't think this is a bug. Looks like my explanation was off. You don't need to include the password in the post body, you can place it in querystring param 'P'. The server side code will fill in the database password value.

**Comment by neylsongularte** [comment]
what do you think about this?

    data.Password = Hash(URL.query.P || data.Password);

**Comment by rchadwic** [comment]
Yeah, that looks fine to me. I don't see any downside.

**Comment by neylsongularte** [comment]
thanks
