### ISSUE TITLE
Delete modifier deletes primitive

### ISSUE THREAD

**Issue by damonregan** [adlnet/Sandbox#272]
Deleting a modifier results in deleting the primitive object it is applied to.

Steps to reproduce:
1.  Create a box
2.  Create a modifier (e.g., bend)
3.  Delete modifer

Result: box is removed from hierarchy.

**Comment by mickmuzac** [comment]
I went ahead and added a delete button to the panels that are generated from modifier or behavior properties. This is probably as straightforward as this is going to get without actually auto-selecting the modifier or behavior whenever its panel is clicked.
