### ISSUE TITLE
Perlin Noise modifier not working?

### ISSUE THREAD

**Issue by damonregan** [adlnet/Sandbox#273]
Not sure what I should be seeing exactly, but creating the perlin noise modifer on a sphere doesn't seem to result in any change no matter the value of the properties.

**Comment by mickmuzac** [comment]
There's a possibility that this could be related to #228.

**Comment by damonregan** [comment]
Duplicates existing issue #237.  Closing.

**Comment by rchadwic** [comment]
You know, I don't think this is actually related to #228. It should do SOMETHING, or it needs to be removed from the menus.
