### ISSUE TITLE
Cannot find module "sandbox-assets-server'

### ISSUE THREAD

**Issue by wilo1** [adlnet/Sandbox#275]
Hello,
I did a fresh install today on a new computer using the lastest zip file and am getting the error cannot find module sandbox-assest-server?

**Comment by stevenvergenz** [comment]
You ran `npm install`, right? Downloaded all the dependencies? If so, did that throw any errors? And what OS and node.js version are you running?

**Comment by stevenvergenz** [comment]
Also, did you mistype the name of the package in your title and message? I've verified that npm will download the correctly-spelled package.

**Comment by wilo1** [comment]
Yes I ran npm. I just downloaded node from the main node site. I am on Windows 8.1 with npm -v
2.14.2. When I start up the sandbox I get part way through and then it says

info: Welcome to Sandbox.
Type "create application" to create your first app.
info: Type "help" for a list of commands.

warn: loading config from ./config.json
error: Could not read config file. Loading defaults.
info: LogLevel = 1 0
info: Versioning is off.
info: Set appPath to /adl/sandbox
/adl/sandbox
info: DAL Startup
./DB_nedb.js
error: uncaughtException: Cannot find module 'sandbox-asset-server' date=Wed Oct
 14 2015 16:24:22 GMT-0400 (Eastern Daylight Time), pid=21164, uid=null, gid=nul
l, cwd=C:\Sandbox-master, execPath=C:\Sandbox-master\node.exe, version=v4.0.0, a
rgv=[C:\Sandbox-master\node.exe, C:\Sandbox-master\app.js], rss=55382016, heapTo
tal=58187520, heapUsed=27577600, loadavg=[0, 0, 0], uptime=718043.4558934, trace
=[column=15, file=module.js, function=Function.Module._resolveFilename, line=336
, method=Module._resolveFilename, native=false, column=25, file=module.js, funct
ion=Function.Module._load, line=286, method=Module._load, native=false, column=1
7, file=module.js, function=Module.require, line=365, method=require, native=fal
se, column=17, file=module.js, function=require, line=384, method=null, native=f
alse, column=25, file=C:\Sandbox-master\support\server\sandbox.js, function=null
, line=243, method=null, native=false, column=20, file=C:\Sandbox-master\node_mo
dules\mkdirp\index.js, function=null, line=20, method=null, native=false, column
=15, file=fs.js, function=FSReqWrap.oncomplete, line=82, method=oncomplete, nati
ve=false], stack=[Error: Cannot find module 'sandbox-asset-server',     at Funct
ion.Module._resolveFilename (module.js:336:15),     at Function.Module._load (mo
dule.js:286:25),     at Module.require (module.js:365:17),     at require (modul
e.js:384:17),     at C:\Sandbox-master\support\server\sandbox.js:243:25,     at
C:\Sandbox-master\node_modules\mkdirp\index.js:20:20,     at FSReqWrap.oncomplet
e (fs.js:82:15)]
error:  code=MODULE_NOT_FOUND
error: Error: Cannot find module 'sandbox-asset-server'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Sandbox-master\support\server\sandbox.js:243:25
    at C:\Sandbox-master\node_modules\mkdirp\index.js:20:20
    at FSReqWrap.oncomplete (fs.js:82:15)
warn: email system not configured

**Comment by stevenvergenz** [comment]
Can you post the output of `npm install sandbox-asset-server`?

**Comment by wilo1** [comment]
C:\Sandbox-master>npm install sandbox-asset-server
-
> sqlite3@3.0.10 install C:\Sandbox-master\node_modules\sandbox-asset-server\nod
e_modules\sqlite3
> node-pre-gyp install --fallback-to-build

'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Sandbox-master\\node.exe" "C:\\Sandbox-master\\node_modules\\
npm\\bin\\npm-cli.js" "install" "sandbox-asset-server"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fal
lback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Sandbox-master\npm-debug.log

**Comment by stevenvergenz** [comment]
When you try to run the sandbox, do you type `node` or `nodejs`?

**Comment by wilo1** [comment]
node app.js as per the instructions on the install page. Should it be something else now?

**Comment by NikolaySuslov** [comment]
You have node v4 installed, but sqlite3@3.0.10 which is used in
sandbox-asset-server
is compatible with for node v0.12.x.
The sandbox-asset-server should be updated to sqlite3@3.1.0, or you could
downgrade the node.

Regards,
Nikolai

**Comment by wilo1** [comment]
You mean downgrade to this version of node?  https://nodejs.org/dist/v0.12.0/   It would be good to make this update in the master.

**Comment by NikolaySuslov** [comment]
Yes, but it will be better to update the sandbox-asset-server to support
the latest node version also. I just have created a pull request.

**Comment by wilo1** [comment]
Thanks so much for your help! It's working now that I downgraded to https://nodejs.org/dist/v0.12.0/x64/node-v0.12.0-x64.msi

**Comment by stevenvergenz** [comment]
Thanks @NikolaySuslov , I've merged your pull request. @wilo1 , go ahead and run `npm install` again, and it'll update your version of the asset server. Additionally, since there is an outstanding bug with that module that affects some systems, I've added a failure mode to the Sandbox so it will still run without an asset server.
