### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by bob-ludvigsen** [adlnet/Sandbox#285]
If "log out" is clicked in editor mode, you are not actually logged out, you just leave the editor.

/Bob

**Comment by rchadwic** [comment]
Yeah - I'm open to suggestions on that. I'm not sure a "leave world" button makes sense either, but I don't think that the in-editor link should remove your session cookie for the whole site. Perhaps we should just remove that completely. What do you think?

**Comment by bob-ludvigsen** [comment]
Well; I think one button is sufficient (the one with the door that is always visible). So in my opinion it would be fine to remove the "Log Out" button.

**Comment by rchadwic** [comment]
Agreed. Addressed in efef64400f5dae6d1ff80840b3652df82d38820d
