### ISSUE TITLE
Avatar bone

### ISSUE THREAD

**Issue by wilo1** [adlnet/Sandbox#295]
I have it resolved now So you can close this issue. Thanks for your help!

**Comment by rchadwic** [comment]
Thanks for these updates. I'm pushing a commit into Master to deal with the last 2 issues - can you test for me? 

The bone selection handles should be disabled completely - the code that creates them was removed...... 

Can you check lines 1772 in support/client/lib/vwf/model/threejs/sceneManager/_THREERayTracer.js?

You should see that `this.buildSelectionHandles();` is commented out....

**Comment by wilo1** [comment]
Yes it's commented out. The fixes you just pushed to the master are still not working. The bones box still shows up.

**Comment by rchadwic** [comment]
Thanks. I realize now that that particular line is not the problem. Can you verify that you have the changes from #e17932bb95868cd6, and that you're cache is disables such that you are sure those changes are getting down to the client? Also, for now, don't run the server with the -build flag, because that will need to be cleaned and rebuild as we make changes.

**Comment by wilo1** [comment]
It's working now for the bones. The box is gone. How do I disable the -build flag when running the server? So the paint tool and other issues mentioned ( obj load from url are still broken)

**Comment by rchadwic** [comment]
Can you check that the tool is working? It may be missing its texture, but otherwise should work. See 7a67aa0ed4a

**Comment by wilo1** [comment]
The paint tool now works. Thanks! I still have some other issues as follows
1- any terrain that was previously created is not loading. Was the engine reworked? This is with height-maps I created. Maybe it's because this is a local copy? I can import the texture to recrete a terrain but it does not preserve all the existing data that was already set up for the terrain. 
2- the bottom play buttons are not working despite doing a hard reload. I will double check that I have all the changes.
So the terrain is the last issue now.

**Comment by wilo1** [comment]
Oh and the fact that in the texture selector now for applying textures there is no image preview anymore. That was a great feature and I am sure our students could benefit from seeing the preview again.

**Comment by wilo1** [comment]
Okay, the terrain is working. I had not moved over the correct heightmap. Easy fix. As for those sprites, that baffles me because they are in the right folder. So I guess the last question I have is in regards to the material editor. Is there no image preview now? Previously there was. Here is what I see now with no preview.
![preview](https://cloud.githubusercontent.com/assets/6297072/16497658/22c5deb0-3ec6-11e6-9d80-b2a702530257.jpg)

**Comment by rchadwic** [comment]
@stevenvergenz Can you take a look at this? I know that I see thumbnails in my local install, but I'm unclear on the details of the refactor for the MapBrowser.

**Comment by wilo1** [comment]
Any idea why in published worlds the avatar is now in lock down and can't move? Not a thing was changed with the settings.

**Comment by stevenvergenz** [comment]
It looks like you're using the built-in asset server for these, right? Thumbnails will only appear in the texture picker if you have explicitly uploaded a thumbnail from the assets panel. The Sandbox doesn't generate thumbnails on the fly.

**Comment by wilo1** [comment]
Oh. okay.

**Comment by wilo1** [comment]
I also identified what was happening with the avatar lockdown. I had an old publish setting file it was reading. I replaced that and all is well. If I can just get the play buttons to show up we can close this issue. :=)
